services:
  postgres:
    image: postgres:17-alpine
    container_name: qr-postgres
    environment:
      POSTGRES_DB: qr_backend
      POSTGRES_USER: qr_user
      POSTGRES_PASSWORD: qr_password
    ports:
      - "5433:5432"
    volumes:
      - qr_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U qr_user -d qr_backend"]
      interval: 5s
      timeout: 5s
      retries: 10

  mailhog:
    image: mailhog/mailhog:v1.0.1
    container_name: qr-mailhog
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  qr_postgres_data:
